# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - pet-cleanic-app/*

pr: none # will disable PR builds (but not CI builds)
  
variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  target: $(build.artifactstagingdirectory)
  artifact: AM
  

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
    
  - task: Docker@2
    inputs:
      containerRegistry: 'newDockerServiceConnection'
      repository: 'seethai/dufryregistry1'
      command: 'buildAndPush'
      Dockerfile: $(dockerfilePath)
      tags: |
          $(tag)
    
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: 'newDockerServiceConnection'
  - task: trivy@1
    inputs:
      version: 'latest'
      image: 'seethai/dufryregistry1/$(tag)'

  
  #- task: CmdLine@2
  #  displayName: DOWNLOAD AND INSTALL AQUASEC TRIVY
  # inputs:
  #   script: |
  #    sudo apt-get install wget apt-transport-https gnupg lsb-release
  #    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
  #    echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
  #    sudo apt-get update
  #    sudo apt-get install trivy
  #    trivy -v
  #    pwd
  
  
  #- task: CmdLine@2
  #  displayName: RUN AQUASEC TRIVY SCAN AND COPY TO ARTIFACTS STAGING DIRECTORY
  #  inputs:
  #    script: |
  #     trivy image --exit-code 0 --severity LOW,MEDIUM seethai/dufry-registry:$(tag) > low-med.txt
  #     trivy image --exit-code 1 --severity HIGH,CRITICAL seethai/dufry-registry:$(tag) > high-critical.txt
  #     ls -l
  #     cp -rvf *.txt $(target)
  
  #- task: PublishBuildArtifacts@1
  # displayName: PUBLISH ARTIFACTS
  # inputs:
  #   targetPath: '$(target)'
  #   artifactName: '$(artifact)'

 


