# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
#  https://docs.microsoft.com/azure/devops/pipelines/languages/java 

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - pet-cleanic-app/*

pr: none # will disable PR builds (but not CI builds)
  
# variables:
  # MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  # MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  # dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  # tag: '$(Build.BuildId)'
  # target: $(build.artifactstagingdirectory)
  # artifact: AM
pool:
  vmImage: 'ubuntu-latest'
  timeoutInMinutes: 20 # how long to run the job before automatically cancelling
  

steps:
  # - task: Cache@2
  #   inputs:
  #     key: 'maven | "$(Agent.OS)" | **/pom.xml'
  #     restoreKeys: |
  #       maven | "$(Agent.OS)"
  #       maven
  #     path: $(MAVEN_CACHE_FOLDER)
  #   displayName: Cache Maven local repo

  # - task: Maven@3
  #   inputs:
  #     mavenPomFile: 'pom.xml'
  #     publishJUnitResults: true
  #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #     javaHomeOption: 'JDKVersion'
  #     jdkVersionOption: '1.17'
  #     mavenVersionOption: 'Default'
  #     mavenOptions: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  #     mavenAuthenticateFeed: false
  #     effectivePomSkip: false
    
  # - task: Docker@2
  #   inputs:
  #     containerRegistry: 'newDockerServiceConnection'
  #     repository: 'seethai/dufryregistry2'
  #     command: 'buildAndPush'
  #     Dockerfile: $(dockerfilePath)
  #     tags: |
  #         $(tag)
    
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: 'DockerServiceConnectionMM'

  - task: trivy@1
    inputs:
      version: 'latest'
      image: 'seethai/dotnet1:1.0.0'
      exitCode: '0'
      
