apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dufry-gateway-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "dufry-gateway-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dufry-gateway-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dufry-gateway-service.name" . }}
      annotations:
        timestamp: "{{ date "2006-01-02 15:04:05" .Release.Time }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 30
            initialDelaySeconds: 1200
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
